# Generated by Django 4.2.2 on 2023-06-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downconvert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('LUN', 'Обед'), ('DIN', 'Ужин'), ('BRK', 'Завтрак')], default='BRK', max_length=3, verbose_name='тИП'),
        ),
    ]
